// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using refactorx.DB.MSSQL;

namespace refactorx.Migrations
{
    [DbContext(typeof(RefactorXContext))]
    [Migration("20210907112155_update2")]
    partial class update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("refactorx.DB.MSSQL.Entities.ApplicantEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressCurrent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNILS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("refactorx.DB.MSSQL.Entities.ApplicationEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AnnualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApplicantID")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicationNum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BranchBankID")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditManagerID")
                        .HasColumnType("int");

                    b.Property<int>("CreditType")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlySalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RequestedCurrencyID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScoringDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ScoringStatus")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("ApplicantID");

                    b.HasIndex("ApplicationNum")
                        .IsUnique()
                        .HasFilter("[ApplicationNum] IS NOT NULL");

                    b.HasIndex("BranchBankID");

                    b.HasIndex("RequestedCurrencyID");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("refactorx.DB.MSSQL.Entities.BranchBankEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("BranchBanks");
                });

            modelBuilder.Entity("refactorx.DB.MSSQL.Entities.CreditManagerEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BranchBankID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BranchBankID");

                    b.ToTable("CreditManagers");
                });

            modelBuilder.Entity("refactorx.DB.MSSQL.Entities.CurrencyEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("refactorx.DB.MSSQL.Entities.ApplicationEntity", b =>
                {
                    b.HasOne("refactorx.DB.MSSQL.Entities.ApplicantEntity", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("refactorx.DB.MSSQL.Entities.BranchBankEntity", "BranchBank")
                        .WithMany()
                        .HasForeignKey("BranchBankID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("refactorx.DB.MSSQL.Entities.CurrencyEntity", "RequestedCurrency")
                        .WithMany()
                        .HasForeignKey("RequestedCurrencyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Applicant");

                    b.Navigation("BranchBank");

                    b.Navigation("RequestedCurrency");
                });

            modelBuilder.Entity("refactorx.DB.MSSQL.Entities.CreditManagerEntity", b =>
                {
                    b.HasOne("refactorx.DB.MSSQL.Entities.BranchBankEntity", "BranchBank")
                        .WithMany()
                        .HasForeignKey("BranchBankID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BranchBank");
                });
#pragma warning restore 612, 618
        }
    }
}
